In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_diabetes
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from sklearn.inspection import permutation_importance

In [2]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_diabetes
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
!pip install dice-ml
import dice_ml

Collecting dice-ml
  Downloading dice_ml-0.11-py3-none-any.whl (2.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.5/2.5 MB 10.0 MB/s eta 0:00:00
Requirement already satisfied: jsonschema in /usr/local/lib/python3.10/dist-packages (from dice-ml) (4.19.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from dice-ml) (1.23.5)
Requirement already satisfied: pandas<2.0.0 in /usr/local/lib/python3.10/dist-packages (from dice-ml) (1.5.3)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.10/dist-packages (from dice-ml) (1.2.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from dice-ml) (4.66.1)
Collecting raiutils>=0.4.0 (from dice-ml)
  Downloading raiutils-0.4.1-py3-none-any.whl (17 kB)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas<2.0.0->dice-ml) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas<2.0.0->dice-ml) (2023.3.post1)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from raiutils>=0.4.0->dice-ml) (2.31.0)
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from raiutils>=0.4.0->dice-ml) (1.11.3)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.10/dist-packages (from jsonschema->dice-ml) (23.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.10/dist-packages (from jsonschema->dice-ml) (2023.7.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.10/dist-packages (from jsonschema->dice-ml) (0.30.2)
Requirement already satisfied: rpds-py>=0.7.1 in /usr/local/lib/python3.10/dist-packages (from jsonschema->dice-ml) (0.12.0)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from scikit-learn->dice-ml) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn->dice-ml) (3.2.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas<2.0.0->dice-ml) (1.16.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->raiutils>=0.4.0->dice-ml) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->raiutils>=0.4.0->dice-ml) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->raiutils>=0.4.0->dice-ml) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->raiutils>=0.4.0->dice-ml) (2023.7.22)
Installing collected packages: raiutils, dice-ml
Successfully installed dice-ml-0.11 raiutils-0.4.1

In [4]:
import pandas as pd
from sklearn.preprocessing import StandardScaler


#reading file
file_path = '/content/default of credit card clients (2).xls'

# Read Excel file into a DataFrame
df = pd.read_excel(file_path)

X=df.drop(columns=['Unnamed: 0'])

# continue with preperation
X=X.drop(columns=['Y'])

#get list of feature names
feature_names= X.iloc[0].values
feature_names = np.array(feature_names)
X=X.drop(index=0)

#conitnue processing data
y=df['Y']
y=y.drop(index=0)

y=pd.to_numeric(y)
y.head()
X = X[X['X3'] != 0]
X['X3'] = X['X3'].replace({5: 4, 6: 4})
X = X[X['X4'] != 0]
X['X4'] = X['X4'].replace({4:3,5: 3, 6: 3})
y = y[X.index]  # Update y to match the filtered rows in X
for column in X:
    X[column] = pd.to_numeric(X[column])
    X[column].head()


print(X)
#split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

#
#sensitive_test = X_test['X2']



y.head()

           X1  X2  X3  X4  X5  X6  X7  X8  X9  X10  ...     X14    X15    X16  \
1       20000   2   2   1  24   2   2  -1  -1   -2  ...     689      0      0
2      120000   2   2   2  26  -1   2   0   0    0  ...    2682   3272   3455
3       90000   2   2   2  34   0   0   0   0    0  ...   13559  14331  14948
4       50000   2   2   1  37   0   0   0   0    0  ...   49291  28314  28959
5       50000   1   2   1  57  -1   0  -1   0    0  ...   35835  20940  19146
...       ...  ..  ..  ..  ..  ..  ..  ..  ..  ...  ...     ...    ...    ...
29996  220000   1   3   1  39   0   0   0   0    0  ...  208365  88004  31237
29997  150000   1   3   2  43  -1  -1  -1  -1    0  ...    3502   8979   5190
29998   30000   1   2   2  37   4   3   2  -1    0  ...    2758  20878  20582
29999   80000   1   3   1  41   1  -1   0   0    0  ...   76304  52774  11855
30000   50000   1   2   1  46   0   0   0   0    0  ...   49764  36535  32428

         X17    X18    X19    X20   X21    X22   X23
1          0      0    689      0     0      0     0
2       3261      0   1000   1000  1000      0  2000
3      15549   1518   1500   1000  1000   1000  5000
4      29547   2000   2019   1200  1100   1069  1000
5      19131   2000  36681  10000  9000    689   679
...      ...    ...    ...    ...   ...    ...   ...
29996  15980   8500  20000   5003  3047   5000  1000
29997      0   1837   3526   8998   129      0     0
29998  19357      0      0  22000  4200   2000  3100
29999  48944  85900   3409   1178  1926  52964  1804
30000  15313   2078   1800   1430  1000   1000  1000

[29932 rows x 23 columns]

1    1
2    1
3    0
4    0
5    0
Name: Y, dtype: int64

In [5]:
print(feature_names)

['LIMIT_BAL' 'SEX' 'EDUCATION' 'MARRIAGE' 'AGE' 'PAY_0' 'PAY_2' 'PAY_3'
 'PAY_4' 'PAY_5' 'PAY_6' 'BILL_AMT1' 'BILL_AMT2' 'BILL_AMT3' 'BILL_AMT4'
 'BILL_AMT5' 'BILL_AMT6' 'PAY_AMT1' 'PAY_AMT2' 'PAY_AMT3' 'PAY_AMT4'
 'PAY_AMT5' 'PAY_AMT6']

In [6]:
model= RandomForestClassifier(max_depth=10, min_samples_leaf=2, min_samples_split=5, n_estimators=150)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
y_pred_prob = model.predict_proba(X_test)

# Calculate accuracy score
accuracy = accuracy_score(y_test, y_pred)  # Use binary target variable here
print("Accuracy on Test Data:", accuracy)

Accuracy on Test Data: 0.8187740103557708

In [ ]:
#TO DO
#get minimum and maximum of each continous feature

 X1: Amount of the given credit (NT dollar): it includes both the individual consumer credit and his/her family (supplementary) credit. X2: Gender (1 = male; 2 = female). X3: Education (1 = graduate school; 2 = university; 3 = high school; 4 = others). X4: Marital status (1 = married; 2 = single; 3 = others). X5: Age (year). X6 - X11: History of past payment. We tracked the past monthly payment records (from April to September, 2005) as follows: X6 = the repayment status in September, 2005; X7 = the repayment status in August, 2005; . . .;X11 = the repayment status in April, 2005. The measurement scale for the repayment status is: -1 = pay duly; 1 = payment delay for one month; 2 = payment delay for two months; . . .; 8 = payment delay for eight months; 9 = payment delay for nine months and above. X12-X17: Amount of bill statement (NT dollar). X12 = amount of bill statement in September, 2005; X13 = amount of bill statement in August, 2005; . . .; X17 = amount of bill statement in April, 2005. X18-X23: Amount of previous payment (NT dollar). X18 = amount paid in September, 2005; X19 = amount paid in August, 2005; . . .;X23 = amount paid in April, 2005.

In [9]:
print(X['X5'].max())

79

In [13]:
# Create a DICE data interface
d = dice_ml.Data(dataframe=pd.concat([X,pd.DataFrame({'label':y_train})], axis=1),
                 features={
                   'X1':[X['X1'].min(), X['X1'].max()], 'X5': [X['X5'].min(),X['X5'].max()], 'X12': [X['X12'].min(),X['X12'].max()],
                   'X13':[X['X13'].min(), X['X13'].max()], 'X14': [X['X14'].min(),X['X14'].max()], 'X15': [X['X15'].min(),X['X15'].max()],
                   'X16':[X['X16'].min(), X['X16'].max()], 'X17': [X['X17'].min(),X['X17'].max()], 'X18': [X['X18'].min(),X['X18'].max()],
                   'X19':[X['X19'].min(), X['X19'].max()], 'X20': [X['X20'].min(),X['X20'].max()], 'X21': [X['X21'].min(),X['X21'].max()],
                   'X22':[X['X22'].min(), X['X22'].max()],'X23': [X['X23'].min(),X['X23'].max()]
                   },
                 continuous_features=['X1','X5','X12','X13','X14','X15','X16','X17','X18','X19','X20','X21','X22','X23'],
                 outcome_name='label')

# Create a DICE model interface
m = dice_ml.Model(model=model, backend="sklearn")

# Create a DICE explainer
exp = dice_ml.Dice(d, m)

# Choose a prediction to explain (e.g., the first test data point)
query_instance = X_test.iloc[0:1]

# Generate 10 counterfactual examples
counterfactuals = exp.generate_counterfactuals(query_instance, total_CFs=10, desired_class='opposite',
                                               features_to_vary=['X1', 'X6', 'X7', 'X8', 'X9', 'X10', 'X11','X12','X13','X14','X15','X16','X17','X18','X19','X20','X21','X22','X23'],proximity_weight=5, diversity_weight=5)
counterfactuals2 = exp.generate_counterfactuals(query_instance, total_CFs=10, desired_class='opposite',
                                               features_to_vary=['X1', 'X6', 'X7', 'X8', 'X9', 'X10', 'X11','X12','X13','X14','X15','X16','X17','X18','X19','X20','X21','X22','X23'],proximity_weight=0.3, diversity_weight=2)
counterfactuals3 = exp.generate_counterfactuals(query_instance, total_CFs=10, desired_class='opposite',
                                               features_to_vary=['X1', 'X6', 'X7', 'X8', 'X9', 'X10', 'X11','X12','X13','X14','X15','X16','X17','X18','X19','X20','X21','X22','X23'],proximity_weight=0.1, diversity_weight=5)
counterfactuals4 = exp.generate_counterfactuals(query_instance, total_CFs=10, desired_class='opposite',
                                               features_to_vary=['X1', 'X6', 'X7', 'X8', 'X9', 'X10', 'X11','X12','X13','X14','X15','X16','X17','X18','X19','X20','X21','X22','X23'],proximity_weight=0.005, diversity_weight=10)

# List the counterfactual examples
counterfactuals.visualize_as_dataframe()
counterfactuals2.visualize_as_dataframe()
counterfactuals3.visualize_as_dataframe()
counterfactuals4.visualize_as_dataframe()

100%|██████████| 1/1 [00:01<00:00,  1.91s/it]
100%|██████████| 1/1 [00:01<00:00,  1.22s/it]
100%|██████████| 1/1 [00:00<00:00,  1.28it/s]
100%|██████████| 1/1 [00:00<00:00,  1.88it/s]

Query instance (original outcome : 0)

,X1,X2,X3,X4,X5,X6,X7,X8,X9,X10,...,X15,X16,X17,X18,X19,X20,X21,X22,X23,label
0,10000,2,2,1,49,0,0,0,0,0,...,5543,5605,5717,1073,1237,500,300,205,300,0

Diverse Counterfactual set (new outcome: 1)

,X1,X2,X3,X4,X5,X6,X7,X8,X9,X10,...,X15,X16,X17,X18,X19,X20,X21,X22,X23,label
0,10000,2,2,1,49,5,0,0,0,0,...,5543,5605,5717,1073,1237,500,54701,205,300,1
1,10000,2,2,1,49,3,0,0,0,0,...,5543,5605,5717,1073,1237,500,300,205,300,1
2,10000,2,2,1,49,2,0,0,0,0,...,5543,5605,5717,710867,1237,500,300,205,300,1
3,724731,2,2,1,49,4,0,0,0,0,...,5543,5605,5717,1073,1237,500,300,205,300,1
4,10000,2,2,1,49,8,0,0,0,0,...,5543,5605,-17876,1073,1237,500,300,205,300,1
5,10000,2,2,1,49,5,0,0,0,0,...,5543,5605,5717,1073,1237,500,300,234692,300,1
6,10000,2,2,1,49,4,0,0,0,0,...,5543,5605,5717,1073,1237,834064,300,205,300,1
7,10000,2,2,1,49,8,0,0,0,0,...,5543,5605,5717,1073,1321516,500,300,205,300,1
8,10000,2,2,1,49,2,0,0,0,0,...,5543,5605,5717,1073,1237,500,300,116712,300,1
9,10000,2,2,1,49,5,0,0,0,0,...,5543,5605,5717,1073,1237,500,300,205,138036,1

Query instance (original outcome : 0)

,X1,X2,X3,X4,X5,X6,X7,X8,X9,X10,...,X15,X16,X17,X18,X19,X20,X21,X22,X23,label
0,10000,2,2,1,49,0,0,0,0,0,...,5543,5605,5717,1073,1237,500,300,205,300,0

Diverse Counterfactual set (new outcome: 1)

,X1,X2,X3,X4,X5,X6,X7,X8,X9,X10,...,X15,X16,X17,X18,X19,X20,X21,X22,X23,label
0,10000,2,2,1,49,3,0,0,0,0,...,5543,5605,5717,1073,1237,551797,300,205,300,1
1,10000,2,2,1,49,2,0,5,0,0,...,5543,5605,5717,1073,1237,500,300,205,300,1
2,10000,2,2,1,49,3,0,0,0,0,...,5543,5605,5717,1073,1237,500,300,205,300,1
3,10000,2,2,1,49,4,0,1,0,0,...,5543,5605,5717,1073,1237,500,300,205,300,1
4,10000,2,2,1,49,7,0,0,0,0,...,5543,5605,5717,1073,1237,500,300,205,300,1
5,10000,2,2,1,49,3,0,0,0,0,...,5543,5605,5717,1073,1237,500,300,205,300,1
6,10000,2,2,1,49,8,0,0,0,0,...,5543,5605,5717,1073,1237,500,300,205,300,1
7,10000,2,2,1,49,6,0,0,0,0,...,5543,5605,5717,1073,1237,500,116223,205,300,1
8,10000,2,2,1,49,8,0,0,0,0,...,5543,5605,-170205,1073,1237,500,300,205,300,1
9,10000,2,2,1,49,8,0,0,0,0,...,5543,5605,5717,1073,1237,500,300,205,300,1

Query instance (original outcome : 0)

,X1,X2,X3,X4,X5,X6,X7,X8,X9,X10,...,X15,X16,X17,X18,X19,X20,X21,X22,X23,label
0,10000,2,2,1,49,0,0,0,0,0,...,5543,5605,5717,1073,1237,500,300,205,300,0

Diverse Counterfactual set (new outcome: 1)

,X1,X2,X3,X4,X5,X6,X7,X8,X9,X10,...,X15,X16,X17,X18,X19,X20,X21,X22,X23,label
0,10000,2,2,1,49,7,0,0,0,0,...,5543,774524,5717,1073,1237,500,300,205,300,1
1,10000,2,2,1,49,7,0,0,0,0,...,5543,5605,5717,1073,1237,500,300,205,300,1
2,10000,2,2,1,49,4,0,0,-1,0,...,5543,5605,5717,1073,1237,500,300,205,300,1
3,10000,2,2,1,49,3,0,0,0,-2,...,5543,5605,5717,1073,1237,500,300,205,300,1
4,10000,2,2,1,49,8,0,0,0,0,...,5543,5605,858814,1073,1237,500,300,205,300,1
5,10000,2,2,1,49,2,0,0,0,0,...,5543,786645,5717,1073,1237,500,300,205,300,1
6,10000,2,2,1,49,7,0,0,0,0,...,707607,5605,5717,1073,1237,500,300,205,300,1
7,706156,2,2,1,49,2,0,0,0,0,...,5543,5605,5717,1073,1237,500,300,205,300,1
8,10000,2,2,1,49,6,0,0,0,0,...,5543,5605,5717,1073,1237,686413,300,205,300,1
9,10000,2,2,1,49,7,0,0,0,0,...,5543,5605,5717,1073,1237,500,515137,205,300,1

Query instance (original outcome : 0)

,X1,X2,X3,X4,X5,X6,X7,X8,X9,X10,...,X15,X16,X17,X18,X19,X20,X21,X22,X23,label
0,10000,2,2,1,49,0,0,0,0,0,...,5543,5605,5717,1073,1237,500,300,205,300,0

Diverse Counterfactual set (new outcome: 1)

,X1,X2,X3,X4,X5,X6,X7,X8,X9,X10,...,X15,X16,X17,X18,X19,X20,X21,X22,X23,label
0,10000,2,2,1,49,3,0,0,0,3,...,5543,5605,5717,1073,1237,500,300,205,300,1
1,10000,2,2,1,49,4,0,0,0,0,...,5543,5605,5717,1073,1237,500,300,154340,300,1
2,10000,2,2,1,49,4,0,0,0,0,...,5543,5605,5717,1073,1237,325247,300,205,300,1
3,10000,2,2,1,49,4,0,0,0,0,...,5543,5605,5717,1073,1237,500,300,205,300,1
4,10000,2,2,1,49,2,0,0,0,0,...,5543,5605,5717,1073,1237,500,300,205,300,1
5,10000,2,2,1,49,5,0,0,0,0,...,5543,5605,5717,1073,1672825,500,300,205,300,1
6,10000,2,2,1,49,3,0,0,8,0,...,5543,5605,5717,1073,1237,500,300,205,300,1
7,10000,2,2,1,49,6,0,0,0,0,...,5543,5605,5717,1073,1237,500,300,205,300,1
8,10000,2,2,1,49,7,0,0,0,0,...,5543,5605,816942,1073,1237,500,300,205,300,1
9,10000,2,2,1,49,8,0,0,0,-2,...,5543,5605,5717,1073,1237,500,300,205,300,1